services:
  project_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - JWT_SECRET_KEY
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_PASSWORD
      - FROM_EMAIL

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d tokenDB" ]
      interval: 10s
      timeout: 5s
      retries: 5
  migration:
    image: gomicro/goose
    command: goose -dir /app/migrations postgres "postgresql://admin:admin@postgres:5432/tokenDB?sslmode=disable" up
    volumes:
      - ./internal/database/migrations:/app/migrations
    depends_on:
      postgres:
        condition: service_healthy