basePath: /
definitions:
  handlers.refreshInput:
    properties:
      refresh_token:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: TestTask
paths:
  /get-tokens/{user_id}:
    get:
      description: get access and refresh tokens via user_id
      parameters:
      - description: ID of the user
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Create tokens
      tags:
      - tokens
  /refresh:
    post:
      consumes:
      - application/json
      description: get access and refresh tokens via user_id
      parameters:
      - description: Данные для регистрации пользователя
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/handlers.refreshInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Refresh tokens
      tags:
      - tokens
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
